### ISSUE TITLE
Issues running jit-diffs on windows

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/jitutils#1]
Hit a couple of issues using this:

* Seems like JIT_DASM_ROOT must be set or app crashes.
* Windows requires .exe suffix for tools
* App should validate `git` is on path up front instead of crashing after running base set
* Framework DLL list seems outdated. Seems like you could just mine the test root.

**Comment by AndyAyersMS** [comment]
@russellhadley FYI...

I may work up some fixes.

**Comment by russellhadley** [comment]
@AndyAyersMS the frame work DLLs come via package so to update you only need to update the project.json, but the fx is only there to be used if CORE_ROOT isn't if you specify --core_root <blah> then that's where the framework dlls will come from.

**Comment by russellhadley** [comment]
Framework update issues tracked by #13.  Closing remaining.
