### ISSUE TITLE
Describe usage of JIT-diff with protonjit

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/jitutils#111]
It is not clear form the documentation how to use JIT diff for arm64.  

Dotnet CLI tools are not available so presumably it is intended to be run on amd64 Unix/Windows.

This may be a s simple as defining AltJIT, but it would be nice to have explicit instructions.

**Comment by sdmaclea** [comment]
@BruceForstall This is probably trivial for you to describe to me.

**Comment by BruceForstall** [comment]
You're right, it would be useful to document all this.

For now:
1. On Windows, build .NET Core for x64
2. `set COMPlus_AltJit=*`
3. `set COMPlus_AltJitName=protononjit.dll`
4. Run jit-diff (hopefully the instructions [here](https://github.com/dotnet/jitutils) are sufficient)

**Comment by BruceForstall** [comment]
Perhaps it's still not documented well enough, but with https://github.com/dotnet/jitutils/pull/124, it's at least easy: just pass the "--altjit" arg. So I'm going to close this issue.
