### ISSUE TITLE
Target netcoreapp2.0 by default

### ISSUE THREAD

**Issue by sbomer** [dotnet/jitutils#116]
At some point we should update jitutils to default to targeting netcoreapp2.0, so that the build scripts "just work" with a .NET Core 2.0 cli install.

This will be a "breaking change" to the build steps, requiring an update to the 2.0 cli, and will probably require minor changes to the jit-format jobs.

See https://github.com/dotnet/jitutils/pull/115 for some discussion.

**Comment by sandreenko** [comment]
Thanks, have checked that it works for me. It only works from "Developer Command Promt", when the standard cmd shows: "There was an error running CMake to generate compile_commands.json. Please do a full build to generate a build log."

**Comment by BruceForstall** [comment]
@sbomer This can be closed now, right?

**Comment by BruceForstall** [comment]
I think this is no longer an issue.
