### ISSUE TITLE
Update framework assembly list

### ISSUE THREAD

**Issue by russellhadley** [dotnet/jitutils#13]
Update framework assembly list.  There are two options here.  Update the baked in list based on what shipped in v1 or make it dynamic based on what's available in the specified core_root directory.

**Comment by russellhadley** [comment]
@sbomer I think you already fixed this.

**Comment by sbomer** [comment]
We talked about it, but I haven't fixed it yet. Will do. :)

**Comment by sbomer** [comment]
Fixed: [70](https://github.com/dotnet/jitutils/pull/70)
