### ISSUE TITLE
jit-diff: implement better cancellation mechanism

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/jitutils#151]
Seems like it takes multiple ^C and a long time to bring jit-diffs to a stop. When you kick one of these off with big assembly lists and things go very wrong right away it should be easier to cancel the whole thing.

I had some prototypes where I implemented the ^C handler and passed cancellation tokens around in jit-diffs, but given the interprocess way this all plays out we likely also need to plumb cancellation events down into the guts of jit-dasm and pmi. Upper layers can pass the event names down to lower layers as optional args or something.

**Comment by mikedn** [comment]
>  Upper layers can pass the event names down to lower layers as optional args or something.

Events as in `EventWaitHandle`? Note that these do not support names on non-Windows platforms: https://github.com/dotnet/coreclr/blob/e32feb0120e74178ef03c5c65b06022666470177/src/System.Private.CoreLib/shared/System/Threading/EventWaitHandle.Windows.cs#L21-L26

Normally you'd just Ctrl-C the child process but it seems that you can't do that easily. Neither the `Command` class that is currently used nor `Process` seem to have a way to send Ctrl-C to the process.

**Comment by AndyAyersMS** [comment]
I guess global named mutexes could work, and they seem to be more broadly supported.
* parent creates and holds mutex, also sets up cancellation token for its tasks
* parent tasks that invoke commands pass the mutex name down to child processes
* on ^C parent releases mutex and cancels its own tasks
* child tasks open mutex, poll to obtain mutex w/timeout or have watchdog thread that tries to obtain it.
* if a child process ever gets the mutex it immediately releases it and stops running
* ditto for grandchild processes

**Comment by mikedn** [comment]
> if a child process ever gets the mutex it immediately releases it and stops running

Might be slightly easier to just close the mutex without releasing. This should result in an `AbandonedMutexException` being thrown in the waiting threads, without requiring them to also release the mutex. Anyway when dealing with cross process mutexes you need to be prepared to handle such an exception.

**Comment by AndyAyersMS** [comment]
Suspect my issues with cancellation happen because I've enabled "quick edit mode" in my command windows.  So Ctrl-C gets reinterpreted. There is a bit of a hacky workaround -- we can change wrapper.bat to redirect stdin:
```
dotnet.exe %~d0%~pn0.dll %* < nul:
```
With that workaround, or with quick edit disabled, Ctrl-C seems to kill off the entire process tree immediately.

Ctrl-Break also results in immediate termination, with or without quick edit and/or the workaround.
