### ISSUE TITLE
Improve jit-dasm performance

### ISSUE THREAD

**Issue by mikedn** [dotnet/jitutils#161]
It looks like jit-dasm consumes a lot of CPU:
![jit-dasm](https://user-images.githubusercontent.com/9973420/44296915-8d296e00-a2d0-11e8-92b8-49eb076cb3ac.png)

And that's when running it sequentially. In parallel you end up with multiple instances of jit-dasm that each take 17% CPU...

As far as I can tell this is due to routing the crossgen output through it. It would be better if the crossgen output goes straight to a file. Unfortunately there doesn't seem to be an easy way to do that:
* the current approach is dictated by `Microsoft.DotNet.Cli.Utils.Command` works, it doesn't appear to offer any other option
* `System.Diagnostics.Process` doesn't seem to be any better, it handles redirection internally as well and gives you the pipe streams, it doesn't give you the opportunity to provide your own stream.
* PInvoke-ing native OS functionality would do the job but it's kind of hairy, especially if you want to make this work on both Windows and Linux.
* Another option would be to modify crossgen to accept a command line option (or env var?) telling it where to write the disassembly. After all, native compilers do offer such options (e.g. MSVC's `/Fa`). But what about PMI? I'd guess the env var would work for it too but not the command line option.
* Yet another option would be to take advantage of the native shell redirection capabilities. Starting `crossgen foobar.dll > out.dasm` should probably do it. It's still platform dependent but the only difference is probably `cmd -c blah` vs. `sh -c blah`.

**Comment by mikedn** [comment]
> Yet another option would be to take advantage of the native shell redirection capabilities. Starting crossgen foobar.dll > out.dasm should probably do it. It's still platform dependent but the only difference is probably cmd -c blah vs. sh -c blah.

I did a quick experiment with that on Windows, works fine - jit-dasm consumes 0% CPU while running crossgen. This might turn out to be the best option as it seems easier to implement.

**Comment by mikedn** [comment]
I've been using a modified `jit-dasm` that takes advantage of `COMPlus_JitStdOutFile` for some time now and it works pretty well.

The question is - what to do with the crossgen's own output? The JIT stdout file contains only the JIT dump, should `jit-dasm` save the crossgen output to a file as well? Or just display it on console? Not that there's anything interesting in the crossgen output...

Also, should the use of `COMPlus_JitStdOutFile` be conditioned by a `jit-dasm` command line option? So it can still work if using an older JIR build?

cc @AndyAyersMS @BruceForstall

**Comment by AndyAyersMS** [comment]
I don't think we care that much, though crossgen can eat some jit failures and it might be nice to see the messages for those. I suppose it's best to save it to some other file (same name, different suffix) and just leave it there in the output dir. It is typically not very much text.

For core we could detect the runtime version and just change behavior -- 2.2 or older, don't use the redirect, 3.0 and later, use it...

I know Bruce had some hopes that jit-dasm would work on desktop too but I'm fuzzy on how realistic this is -- probably needs quite a bit more customization down low somewhere anyways.

**Comment by BruceForstall** [comment]
If there's a VM assert, that wouldn't show up in JitStdOutFile, right? So we want to catch those. I suppose having two separate files is ok.

Seems like the "cmd -c blah" option isn't so bad, IMO. Not sure I have a strong opinion here (I also haven't done enough jit-dasm recently to notice it being slow).

**Comment by mikedn** [comment]
>  I suppose it's best to save it to some other file (same name, different suffix) and just leave it there in the output dir. It is typically not very much text.

Maybe there should be a single file, when diffing tests you already get a ton of files and doubling the number of files doesn't sound too appealing.

> For core we could detect the runtime version and just change behavior -- 2.2 or older, don't use the redirect, 3.0 and later, use it...

I'm not sure I understand, how's jit-dasm supposed to know the version?

> If there's a VM assert, that wouldn't show up in JitStdOutFile, right? 

No, the assert is printed by the VM to stderr so it has nothing to do with JitStdOutFile. The strange thing is that I don't see the assert anywhere even in the current implementation that does not use JitStdOutFile. My local implementation doesn't show it either, I was expecting to appear in the console because I removed the redirects. Strange.

> Seems like the "cmd -c blah" option isn't so bad, 

That doesn't take care of the lack of stdout buffering in the JIT. JitStdOutFile handles both buffering and the high jit-dasm pipe overhead.

> I also haven't done enough jit-dasm recently to notice it being slow

On my machine (4 cores) FX diff takes 320 seconds (only the dasm part). With JitStdOutFile it takes only 117 seconds.

**Comment by BruceForstall** [comment]
> doubling the number of files doesn't sound too appealing.

I'm personally not too worried about that, since if we have one file with the JitStdOutFile output, and one with all other redirected output (to catch stderr, VM asserts, etc.), then presumably the 2nd file will be very small, so diff'ing them will be super fast. Maybe we could name them with a common prefix (e.g., "_.") so they sort out of the way, if it's clutter to have their filenames intermixed with the .dasm.
