### ISSUE TITLE
Stable PMI method numbers

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/jitutils#174]
When I use PMI, I typically want to do:
1. PMI PrepAll foo.dll
2. Find the method number I'm interested in.
3. Set COMPlus variables.
4. PMI PrepOne foo.dll method_number_of_interest

However, it looks like the numbers between "PMI PrepAll" and "PMI PrepOne" are not stable: the numbers don't refer to the same method.

Why are the numbers different?

E.g., in PrepAll:
```
PREPALL type# 202 method# 3760 System.Data.SqlTypes.SqlDecimal::MpMove
```

In "PrepOne 3760":
```
PREPONE type# 202 method# 3760 System.Data.SqlTypes.SqlDecimal::Add
```

**Comment by BruceForstall** [comment]
@AndyAyersMS ?

**Comment by AndyAyersMS** [comment]
They use the same visitor pattern to enumerate types and methods so they should match up -- maybe an off by one error somewhere? Where does `SqlDecimal::Add` fall in the prepall sequence?

**Comment by AndyAyersMS** [comment]
Hmm, not off by one.

I doubt inlining or class loading is the culprit here, but I don't have any other hypotheses. Perhaps we can have prepone print out the names of the methods it is skipping and diff that versus prepall to see where they diverge...

**Comment by AndyAyersMS** [comment]
Hmm, when I try this I get matching numbers.
```
PREPALL type# 202 method# 3756 System.Data.SqlTypes.SqlDecimal::AdjustScale
PREPALL type# 202 method# 3757 System.Data.SqlTypes.SqlDecimal::AdjustScale
PREPALL type# 202 method# 3758 System.Data.SqlTypes.SqlDecimal::ConvertToPrecScale
PREPALL type# 202 method# 3759 System.Data.SqlTypes.SqlDecimal::LAbsCmp
PREPALL type# 202 method# 3760 System.Data.SqlTypes.SqlDecimal::MpMove

PREPONE type# 202 method# 3756 System.Data.SqlTypes.SqlDecimal::AdjustScale
PREPONE type# 202 method# 3757 System.Data.SqlTypes.SqlDecimal::AdjustScale
PREPONE type# 202 method# 3758 System.Data.SqlTypes.SqlDecimal::ConvertToPrecScale
PREPONE type# 202 method# 3759 System.Data.SqlTypes.SqlDecimal::LAbsCmp
PREPONE type# 202 method# 3760 System.Data.SqlTypes.SqlDecimal::MpMove
```
Are you running with tiering disabled?

**Comment by BruceForstall** [comment]
cc @sandreenko

**Comment by sandreenko** [comment]
I think I can repro it on desktop as well.

**Comment by AndyAyersMS** [comment]
Feel free to pull down [my fork](https://github.com/AndyAyersMS/jitutils/pull/new/PrepOneVerbose) and diff the prepall and prepone outputs.

**Comment by BruceForstall** [comment]
Well, now I can't repro the issue. I'm going to close the GitHub issue. @sandreenko feel free to re-open if you have a reliable .NET Core repro.
