### ISSUE TITLE
Include ASP.NET Core assemblies in the standard set

### ISSUE THREAD

**Issue by benaadams** [dotnet/jitutils#189]
When generating the wider set of jit diffs to check; probably should be recentish e.g. from 3.0 [core-sdk](https://github.com/dotnet/core-sdk)

**Comment by AndyAyersMS** [comment]
If you download manually and extract it kind of works... but for some reason the cross-assembly resolution

```
jit-diff diff --base --base_root d:\repos\coreclr2 --diff --pmi --cctors --assembly C:\Users\andya\Downloads\3.0.0-preview-18579-0056
...
Dasm commands returned 13 base failures, 13 diff failures.
Completed PMI Diffs for C:\Users\andya\Downloads\3.0.0-preview-18579-0056 [invoking .cctors] in 223.78s
Diffs (if any) can be viewed by comparing: D:\repos\coreclr\bin\diffs\dasmset_5\base D:\repos\coreclr\bin\diffs\dasmset_5\diff
Analyzing diffs...
PMI Diffs for C:\Users\andya\Downloads\3.0.0-preview-18579-0056 [invoking .cctors] for x64 default jit
Summary:
(Lower is better)
Total bytes of diff: 0 (0.00% of base)
0 total files with size differences (0 improved, 0 regressed), 138 unchanged.
0 total methods with size differences (0 improved, 0 regressed), 28069 unchanged.
Completed analysis in 3.44s

Warning: Failures detected generating asm: 13 base, 13 diff

D:\repos\coreclr>jit-analyze --base D:\repos\coreclr\bin\diffs\dasmset_5\base --diff D:\repos\coreclr\bin\diffs\dasmset_5\diff

Summary:
(Lower is better)

Total bytes of diff: 0 (0.00% of base)

0 total files with size differences (0 improved, 0 regressed), 138 unchanged.

0 total methods with size differences (0 improved, 0 regressed), 28069 unchanged.
```
Typical failure case:
```
ReflectionTypeLoadException Microsoft.AspNetCore.SignalR.Common
ReflectionTypeLoadException Microsoft.AspNetCore.SignalR.Common   ex: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
ReflectionTypeLoadException Microsoft.AspNetCore.SignalR.Common type: JsonUtils
ReflectionTypeLoadException Microsoft.AspNetCore.SignalR.Common type: MemoryBufferWriter
...
````

**Comment by benaadams** [comment]
Ah, I think ASP.NET Core might be on a later Json.NET version; Core_Root includes v 9.0.1 and ASP.NET Core uses v 11.

When copying Core_Root over into a self-contained app normally have to either skip its copy of Json.NET or overwrite it again with a more recent version; not sure what's referecing it from coreclr/fx (guessing a test?) otherwise would bump its version there. /cc @JamesNK @davidfowl

**Comment by benaadams** [comment]
The 2.2.1 "All" meta package might work also; as that pulls in common 3rd party deps too https://www.nuget.org/packages/Microsoft.AspNetCore.All/

Don't think there is an "All" version for 3.0

**Comment by AndyAyersMS** [comment]
CoreCLR tests possibly? external.depproj has
```
    <PackageReference Include="Newtonsoft.Json">
      <Version>9.0.1</Version>
    </PackageReference>
```
Now that we can build with 3.0 we should look into using assembly load contexts (or whatever they are called) to allow arbitrary version loading.

**Comment by benaadams** [comment]
If its easy to bring in the [Microsoft.AspNetCore.All](https://www.nuget.org/packages/Microsoft.AspNetCore.All/) 2.1.1 nuget; then that will also pull in EntityFramework some 3rd party libs e.g. Azure, Redis, DB etc

It might not be the most current (i.e. 3.0) but it should be representative of common patterns in use outside corefx to help see the impact of Jit changes?

ASP.NET Core 3.0 has changed the packaging with it becoming part of the base, to not bring in 3rd party deps by default (hence `.All` being dropped); I believe?

**Comment by benaadams** [comment]
Added PR for version https://github.com/dotnet/coreclr/pull/22060
