### ISSUE TITLE
PMI: consider adding more types to use in instantiations

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/jitutils#198]
Couple of things that would make PMI more useful for catching issues:

* We should be trying both 8 bit and 16 bit short types. Perhaps one of these unsigned. Adding one of each increases the number of methods PMI'd in a checked arm64 corelib from ~26000 to ~31000.
* Would be nice if PMI could figure out how to instantiate they key methods in low-level async processing, eg `AwaitUnsafeOnCompleted`. This would probably require some special purpose pattern matching. When PMI encounters a generic with constraints it has no idea how to create types that will satisfy those constraints.

**Comment by briansull** [comment]
@AndyAyersMS 

To me it appears that #199 completely address this issue.
It adds instantiations for byte and short, an 8-bit and a 16-bit sign type.
This PR also adds AwaitUnsafeOnCompleted support  for a couple of special purpose instantiations.

**Comment by briansull** [comment]
I propose that we close this issue.
