### ISSUE TITLE
Can't get diffs for assemblies with spaces in their names

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/jitutils#200]
This is really a jit issue, but it only impacts jit-dasm-pmi, so opening it here for the time being.

jit-dasm-pmi uses `COMPlus_JitDisasmAssemblies` to limit the disassmbly to specific assemblies, but the jit interprets whitespace in this string as a separator when building the assembly list.

So methods in any assembly with a space in its name won't get disassembled.

Fix is likely to pass an option into the assembly name list parser to consider whitespace significant in some cases?

**Comment by kunalspathak** [comment]
@AndyAyersMS  - I am closing this issue because it looks like it is addressed in https://github.com/dotnet/coreclr/pull/23410. We can re-open if that is not the case.
