### ISSUE TITLE
Update jitutils for new runtime repo structure

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/jitutils#230]
A number of jitutils tools know about the layout of build artifacts and tests in the coreclr repo.

With the consolidation of coreclr into runtime, all this needs updating.

Since jitutils is not branched or officially released, it also would be nice if jitutils tools continued to work with the coreclr repo (might need them for servicing, etc).

**Comment by tannergooding** [comment]
I put up https://github.com/dotnet/jitutils/pull/244 to resolve this.
