### ISSUE TITLE
update PMI assembly set for runtime live-live

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/jitutils#246]
If you run jit-diffs on a live-live build in the runtime repo, you'll see a bunch of assemblies missing from the set we usually process:
```
jit-diff diff --base --base_root c:\repos\runtime1 --diff --diff_root c:\repos\runtime2 --core_root c:\repos\runtime1\artifacts\tests\coreclr\Windows_NT.x64.Checked\tests\Core_Root -o %CD% -t pmi -f

Using --base c:\repos\runtime1\artifacts\bin\coreclr\Windows_NT.x64.Checked
Using --diff c:\repos\runtime2\artifacts\bin\coreclr\Windows_NT.x64.Checked
Using --arch x64
Beginning Crossgen CodeSize Diffs for System.Private.CoreLib.dll, framework assemblies
Warning: can't find framework assembly c:\repos\runtime1\artifacts\tests\coreclr\Windows_NT.x64.Checked\tests\Core_Root\NuGet.Protocol.Core.v3.dll
Warning: can't find framework assembly c:\repos\runtime1\artifacts\tests\coreclr\Windows_NT.x64.Checked\tests\Core_Root\Microsoft.DotNet.ProjectModel.dll
Warning: can't find framework assembly c:\repos\runtime1\artifacts\tests\coreclr\Windows_NT.x64.Checked\tests\Core_Root\NuGet.Packaging.dll
Warning: can't find framework assembly c:\repos\runtime1\artifacts\tests\coreclr\Windows_NT.x64.Checked\tests\Core_Root\NuGet.Frameworks.dll
Warning: can't find framework assembly c:\repos\runtime1\artifacts\tests\coreclr\Windows_NT.x64.Checked\tests\Core_Root\NuGet.ProjectModel.dll
...
```
We should update the set to reflect what's there with the latest repo changes.

**Comment by AndyAyersMS** [comment]
Outline of how to do this update:

* Build release in a clean repo
* Run pmi in count mode over all assemblies in core_root (but not subdirs)
* Filter out any assemblies with zero methods
* Sort remainder by number of methods
* Use that as the list for jit-diff to process

**Comment by erozenfeld** [comment]
@AndyAyersMS Looks like the assembly set has changed again. Should we build the list of assemblies automatically by scanning core_root rather than hard-coding the list?

**Comment by AndyAyersMS** [comment]
I suppose we could, yes.

Sort by file size to get the priority order? Filter out non-assembly PE files during the scan?

**Comment by erozenfeld** [comment]
Yeah, something like that. We can sort by the number of methods as we do today but sorting by size may be good enough. The only problem is that the size may be misleading if we have a mixture of pure IL assemblies and crossgen-ed assemblies.

**Comment by erozenfeld** [comment]
Opened #251.
