### ISSUE TITLE
jit-analyze: add instruction count metric

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/jitutils#266]
Currently, we have a code size metric that is in bytes of code. Add an additional metric that is number of instructions. This can be useful when comparing cross-architecture generated code, such as x64 versus arm64, to avoid to encoding effects. This might also be useful same-architecture.

**Comment by briansull** [comment]
I could work on this issue

**Comment by kunalspathak** [comment]
@briansull  - I almost have a PR ready for this one. Sorry for not informing you earlier.

**Comment by JulieLeeMSFT** [comment]
@briansull @kunalspathak I recommend assigning issues to yourself when you start to look at it in order to avoid overlapped effort.

**Comment by JulieLeeMSFT** [comment]
@kunalspathak It would be useful if you can include the screenshot of output after your change in this issue.

**Comment by kunalspathak** [comment]
Sure.

![image](https://user-images.githubusercontent.com/12488060/92790376-96c31a00-f360-11ea-83a1-2af3651a9615.png)
