### ISSUE TITLE
jit-format fails to determine the OS

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/jitutils#277]
If you don't pass the `--os` argument, jit-format tries to determine the OS by running `dotnet --info` and parsing the `OS Platform` line, e.g.:
```
OS Platform: Windows
```

However, it seems to fail for me. When I manually type `dotnet --info`, I see the `OS Platform` line. But when I alter `jit-format` to print the stdout result of `dotnet --info` and the lines it is matching, the first couple sections of output, including the `OS Platform` line, is missing!

@dotnet/jit-contrib

**Comment by briansull** [comment]
I stepped through this with the RC1 version of .Net 5 and this appears toi be fixed:

![image](https://user-images.githubusercontent.com/11621884/93262007-5eed1580-f758-11ea-937e-671340a37148.png)

Contains:

 OS Platform: Windows

**Comment by briansull** [comment]
I believe that this is fixed in 5.0 RC1
