### ISSUE TITLE
SuperPMI Work Items

### ISSUE THREAD

**Issue by jashook** [dotnet/jitutils#32]
### SuperPMI

We need to create SuperPMI collections for a large amount of code to help with quick assertion checking and asm diffs. The work here is:

| Task | Issue | Time Expected |
| --- | --- | --- |
| Automate the collection | #33 | [PR](https://github.com/dotnet/jitutils/pull/45) |
| Easy superPMI Replay | #35 |  |
| Add collection to DotnetCI | #44 |  |
| Expand collection resources | #34 | `TBD` |
| Fix SuperPMI to use coredis tools, to enable asm diffs | [6942](https://github.com/dotnet/coreclr/issues/6942) | `TBD` |

**Comment by BruceForstall** [comment]
This is obsolete
