### ISSUE TITLE
Initial proposal to automate SuperPMI Collection

### ISSUE THREAD

**Issue by jashook** [dotnet/jitutils#33]
Allow SuperPMI collection to be done automatically over the CoreCLR and CoreFX Repos. Below was the initial proposal for the tool.
## Overview

A managed application to automatically run superPMI using an already built coreclr.
### Example Usage

> SuperPMiCollect.exe x86 checked
### Storage

The superPMI information collected will be stored in Azure Blob Storage. It will be compressed so that the information be stored efficiently. The directory structure will be emulated below in Azure Blob Storage.
### Directory Structure

Blob Storage

```
|--Git Hash
    |--OS
        |--Arch
            |--JITS.zip
            |-- MCH
                  |--Mchfile1.zip
                  |--Mchfile2.zip
                  |--   …
            |--MCH_ASM
                  |--Mchfile1.zip
                  |--MchFile2.zip
                  |--   …
            |--CORE_ROOT.zip
```
### Finding a Sync Point

It will be almost guaranteed to be too wasteful to collect on each checkin, therefore, we need to find a way to sync to a certain changeset, given a git hash. Basically, with some git log parsing we can find the date of both hashes and compare the amount of changes between them. We can walk through the list of hashes we have stored and find the one that is closest to the current hash you are on.

Then you can pull down all of the information for that arch and os.
### Collecting

Collecting can already be done with the collection tool Bruce wrote. We can run it over the over the crossgen of the CoreFX Frameworks, coreclr test run and Roslyn testing to start. See #34 for information on expanding this.

**Comment by BruceForstall** [comment]
Obsolete.
