### ISSUE TITLE
Publish a new version of CoreDisTools NuGet packages

### ISSUE THREAD

**Issue by echesakov** [dotnet/jitutils#349]
I realized that I haven't published a new version of CoreDisTools NuGet packages after updating the LLVM to 13.0 https://github.com/dotnet/jitutils/commit/6fedaca9622e8db51e3f92ff533a8fcb1aceb8e3

In addition to that, we would need to update clrjit2 blob with the newer versions of the libraries (if we want to use the new version with superpmi.py). IIRC, only macos-arm64 `libcoredistools.dylib` was added to the blob storage. Is this correct, @kunalspathak?

**Comment by kunalspathak** [comment]
I see it is uploaded for osx-64 and osx-arm64

**Comment by echesakovMSFT** [comment]
Un-assigning myself
cc @BruceForstall

**Comment by BruceForstall** [comment]
I published the new coredistools from build https://dev.azure.com/dnceng/public/_build/results?buildId=1665935&view=artifacts&pathAsName=false&type=publishedArtifacts to the clrjit blob container (within https://clrjit2.blob.core.windows.net/superpmi/libcoredistools/; coredistools is downloaded from there by superpmi.py if it doesn't find an existing coredistools in Core_Root).

Note that we don't build windows-arm coredistools any more, so I left the old one there.

@dotnet/jit-contrib Let me know if you notice any problems.
