### ISSUE TITLE
SuperPMI fix SuperPMI Asserts and NYIs

### ISSUE THREAD

**Issue by jashook** [dotnet/jitutils#43]
Currently under mac/linux there are a few SuperPMI errors that happen.

Assertions
- [ ] SuperPMI assertion 'EmbedGenericHandle != nullptr' failed ("Encountered an empty LWM while looking for ...")
- [ ] SuperPMI assertion 'GetFieldType != nullptr' failed ("Didn't find anything for 000001C688F60C20")
- [ ] SuperPMI assertion 'CanSkipMethodVerification != nullptr' failed ("Didn't find anything for 00000238DAA9B9F8")

As well, while crossgenning the system frameworks SuperPMI NYIs consistantly with a few helpers not being implemented.

NYIs
- [ ] ERROR: getReadyToRunHelper NYI

**Comment by BruceForstall** [comment]
If this still happens, I'm going to assume we'll open new issues.
