### ISSUE TITLE
Modify jit-dasm to take base/diff jits rather than crossgen

### ISSUE THREAD

**Issue by russellhadley** [dotnet/jitutils#47]
Crossgen has a feature where it *always* looks for the System.Private.CoreLib in the directory where it resides.  Even if it is passed a full path. 

Modify jit-dasm to take a crossgen parameter which points to a single crossgen/System.Private.CoreLib pair and then uses the crossgen -JitPath argument to produce output from a base/diff jit.

This will remove the potential for diffs in System.Private.CoreLib that don't result from the JIT.

**Comment by sbomer** [comment]
pull request: https://github.com/dotnet/jitutils/pull/49
