### ISSUE TITLE
[question] Getting total generated code size from a JitDump

### ISSUE THREAD

**Issue by jamesqo** [dotnet/jitutils#48]
Hi, I was wondering if it's possible to get the total number of bytes of code the JIT produces for a given program, or in other words the sum of the code size of all of the methods it generates. Is there a CLR configuration knob for this, or if not is it possible with the current tooling in this repo?

Thanks!

**Comment by russellhadley** [comment]
@sbomer can you take a look at this?

**Comment by sbomer** [comment]
jit-analyze has some similar functionality. Internally it collects the code size for each method, but currently it uses this show stats for the diff. I'd like to modify jit-analyze to work in two modes: the current base/diff mode, and a single-dasm mode, in which it would output stats (total code size for now) for a single dasm. @russellhadley does that sound all right to you?
