### ISSUE TITLE
jit-format output could be more friendly when errors are detected

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/jitutils#52]
1. It shouldn't print “Clang-Format needs to be rerun in fix mode”.  It should say "Run jit-format -fix -no-tidy" or leave out the -no-tidy part if there are tidy errors.
2. It could maybe print the first X lines of specific error message even in non-verbose mode

**Comment by BruceForstall** [comment]
I had it print:
```
Clang-format found formatting errors.
jit-format found formatting errors. Run:
	jit-format -fix -untidy
```
That doesn't work: the long arguments need double dashes, not single dashes.

@adiaaida

**Comment by adiaaida** [comment]
It's been fixed.
