### ISSUE TITLE
"Command line is too long" error

### ISSUE THREAD

**Issue by russellhadley** [dotnet/jitutils#55]
There have been a number of reports of "command line too long" coming out of the sub tools that jit-diff uses.  Below is one report but there have been others.  Fix would be to find a way to work around this.

<snip>
I tried running the following from PowerShell:

jit-diff diff --analyze --crossgen \git\coreclr\bin\Product\Windows_NT.x64.Checked.master\crossgen.exe --base \git\coreclr\bin\Product\Windows_NT.x64.Checked.master --diff \git\coreclr\bin\Product\Windows_NT.x64.Checked --output \git\Diffs --core_root D:\git\coreclr\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root --test_root D:\git\coreclr\bin\tests\Windows_NT.x64.Checked

I still get the “The command line is too long.” Error.
</snip>

**Comment by sbomer** [comment]
Fixed by [56](https://github.com/dotnet/jitutils/pull/56).
