### ISSUE TITLE
Integrate jit-diff into CI job to allow lab run baseline/diff across lab jobs.

### ISSUE THREAD

**Issue by russellhadley** [dotnet/jitutils#62]
Speed up diff analysis but including it in the lab jobs.  
-  Run .dasm baseline for commit trigger jobs (Linux, Windows x x64, x86, arm64)
-  PR jobs  run diff jobs and compare against merge point where there should be data from the commit job.

**Comment by sbomer** [comment]
work in progress: [8032](https://github.com/dotnet/coreclr/pull/8032)

**Comment by BruceForstall** [comment]
We're not planning to pursue this.
