### ISSUE TITLE
Jit-dasm should use /fragile crossgen

### ISSUE THREAD

**Issue by JosephTremoulet** [dotnet/jitutils#75]
Jit-dasm uses crossgen to avoid having to execute the code, but crossgen has several limitations compared to jitting code.  Crossgen has some sort of /fragile option to lift those constraints, and using this mode would mean the generated diffs would be more representative of diffs that will arise in jitted code.  Presumably it will be interesting to be able to select whether /fragile is desired or not when generating disasm/diffs, and I think that /fragile should be the default.

**Comment by JosephTremoulet** [comment]
It's easy enough to plumb through --fragile (a4ae43b2b68f), but that turns out to be insufficient because /FragileNonVersionable crossgen requires dependencies to be already crossgened so it can find their native image files.  This would require making sure frameworks are crossgened if we want to crossgen benchmarks, making sure frameworks are crossgen'ed in the right order, and doing something about the fact that we currently delete each native image file immediately after generating it (which isn't as straightforward as you'd think because jit-dasm takes responsibility for deleting those files, but jit-diff invokes jit-dasm separately for each assembly [at least for frameworks assemblies], and trying to change that gives "command too long" errors so would need to use response files or something...).

**Comment by JosephTremoulet** [comment]
>  I think that /fragile should be the default

FWIW, I've changed my mind about this as well.  I think it makes sense to look at diffs of ReadyToRun frameworks since that's what ships.  For benchmarks, it would make the most sense to look at jit codegen, but /FragileNonVersionable is something in between ReadyToRun and Jit.  Though /FragileNonVersionable is still likely better for benchmarks than ReadyToRun.

**Comment by russellhadley** [comment]
@JosephTremoulet #99 linking back here for JIT like codegen. 

- I'd like to see more JIT like code gen in crossgen for testing purposes.  For the new optimization levels on your backlog I'd want to use crossgen for stress and "random" seed testing to try and generate more coverage of tiering while maintaining stable repros.
- I'd expect that we would then harness our big scenarios for the above and then be able to do multi optimization level diffs using Azure resources.
- Additionally it'd be super nice to use a pseudo random IBC data input to stress codegen as we make more optimizations in the JIT sensitive to it.

So yes more JIT-like modes and more ability to model/force tiering like execution.  Given how much easier it is to debug/validate crossgen cases, bringing it closer to our JIT codegen, and peak codegen can only help.

For superpmi, I'm curious about making it more generalized such that you could capture a trace on a machine and then use it with the same assemblies to make a *.ni.* image with crossgen that closely follows the trace.  You'd have to go back to tokens, and there'd be some handwaving for some things but it just seems like a slick idea to me.

**Comment by JosephTremoulet** [comment]
> I'd like to see more JIT like code gen in crossge

What would that take to pull off?  How much of the code controlling this is in the JIT, how much in other components?  Is it consolidated somewhere?  Do we have a list of differences written down somewhere?  Configuration flags or #defines that would be referenced in the relevant places?

**Comment by russellhadley** [comment]
I don't think the list is written down anywhere.  There two area that I think matter.  First, the runtime does give different answers about how many indirection to use to use to get a piece of info for AOT vs JIT (some times the jit just get's a constant), that will be difficult to control for (and note that between R2R and Fragile there will differing levels of indirections.)  Second the JIT makes different decisions based on weather it's AOT or JIT.  I'm hoping these are superseded by the opt level definition and we can control that.  I don't think we yet know the extent of the work items so it's a bit of exploring.

**Comment by AndyAyersMS** [comment]
Fragile CoreCLR crossgen is arguably not as fragile as it should be; it still has policies from desktop NGen model where there was some attention paid to serviceability. For instance cross-assembly inlines are inhibited even in /Fragile mode.

Another big area of difference is jit-time dependence on ambient VM state, in particular class init checks. If you don't care about actually needing to run the generated code then perhaps you could suppress those.

**Comment by BruceForstall** [comment]
crossgen is now obsolete
