### ISSUE TITLE
jit-diff should run base and diff jit-dasm in parallel

### ISSUE THREAD

**Issue by mikedn** [dotnet/jitutils#88]
This way you don't have to wait until the entire base dasm is generated to inspect the diff for System.Private.CoreLib (which comes first when doing a fx diff).

Besides, crossgen appears to be single threaded so running 2 crossgens in parallel should speed up things.

Any downsides in doing this?

**Comment by JosephTremoulet** [comment]
> Any downsides in doing this?

Aside from needing to make sure that the console output is intelligible (I'm guessing we'd want line-granularity interleaving with some sort of base/diff prefix to distinguish, to both know what's what and get some incremental indication of progress), nothing comes to my mind.

**Comment by mikedn** [comment]
Another annoying issue is that crossgen outputs the path to the generated image:
```
Native image D:\Projects\coreclr\bin\Product\Windows_NT.x64.Checked\System.Private.CoreLib.ni.dll generated successfully.
```
I need to change the output path so the base and diff crossgen write to different files. And now all .dasm files show up as different in diff tools due to that crossgen message. Yet to figure out a workaround for that. Perhaps simply removing the last line in the produced .dasm files will do.

**Comment by BruceForstall** [comment]
Fixed
