### ISSUE TITLE
jit-diff should show path of base and diff

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/jitutils#92]
To allow for easy cut-and-paste to a directory diff program. e.g.,:
```
To examine diffs, use a command like:
   <diff-program> c:\diffs\base\4 c:\diffs\diff\4

e.g., on Windows:
    windiff c:\diffs\base\4 c:\diffs\diff\4
```

On Windows, our desktop testing infrastructure also automatically detects if the paths are shared, giving a UNC path. This is useful for copy-and-paste of the command to email to others to look at your diffs, e.g.:
```
   windiff \\brucefo1\mydiffs\base\4 \\brucefo1\mydiffs\diff\4
```

**Comment by JosephTremoulet** [comment]
@BruceForstall now that `jit-diff diff` prints the `jit-analyze` invocation at the end (which has these paths), should this be closed?

**Comment by BruceForstall** [comment]
@JosephTremoulet The current output is still not quite copy-and-paste like I would prefer, nor does it look up UNC shares, which is useful.
